---
- name: Install Docker, Docker Compose, and Lazydocker
  hosts: "{{ host | default('none') }}"
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Get latest Lazydocker version
      uri:
        url: https://api.github.com/repos/jesseduffield/lazydocker/releases/latest
        return_content: yes
      register: lazydocker_release

    - name: Download Lazydocker
      get_url:
        url: "https://github.com/jesseduffield/lazydocker/releases/download/{{ lazydocker_release.json.tag_name }}/lazydocker_{{ lazydocker_release.json.tag_name | regex_replace('^v', '') }}_Linux_x86_64.tar.gz"
        dest: /tmp/lazydocker.tar.gz
        mode: '0644'

    - name: Extract Lazydocker
      unarchive:
        src: /tmp/lazydocker.tar.gz
        dest: /usr/local/bin
        remote_src: yes
        creates: /usr/local/bin/lazydocker

    - name: Make Lazydocker executable
      file:
        path: /usr/local/bin/lazydocker
        mode: '0755'

    - name: Remove Lazydocker archive
      file:
        path: /tmp/lazydocker.tar.gz
        state: absent

    - name: Add user to docker group
      user:
        name: "{{ lookup('env', 'ANSIBLE_USER') }}"
        groups: docker
        append: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started
