version: "3.8"

services:
  ansible:
    build:
      context: .
    volumes:
      - .:/ansible
      - /Users/sh/.ssh/id_rsa:/root/.ssh/id_rsa:ro
    working_dir: /ansible
    stdin_open: true
    tty: true




