---
- name: Create and enable 2GB swap file
  hosts: "{{ host | default('none') }}"
  become: yes

  vars:
    swap_file_path: /swapfile
    swap_file_size_mb: 2048

  tasks:
    - name: Check if swap file already exists
      stat:
        path: "{{ swap_file_path }}"
      register: swap_file_check

    - name: Check current swap status
      command: swapon --show
      register: swap_status
      changed_when: false
      failed_when: false

    - name: Display current swap status
      debug:
        msg: "{{ swap_status.stdout if swap_status.stdout else 'No swap currently enabled' }}"

    - name: Create swap file
      command: dd if=/dev/zero of={{ swap_file_path }} bs=1M count={{ swap_file_size_mb }}
      when: not swap_file_check.stat.exists

    - name: Set swap file permissions
      file:
        path: "{{ swap_file_path }}"
        mode: '0600'
        owner: root
        group: root

    - name: Format swap file
      command: mkswap {{ swap_file_path }}
      when: not swap_file_check.stat.exists

    - name: Enable swap file
      command: swapon {{ swap_file_path }}
      when: swap_file_path not in swap_status.stdout

    - name: Add swap to fstab for persistence across reboots
      lineinfile:
        path: /etc/fstab
        line: "{{ swap_file_path }} none swap sw 0 0"
        state: present
        regexp: "^{{ swap_file_path }}"

    - name: Set swappiness to 10 (recommended for servers)
      sysctl:
        name: vm.swappiness
        value: '10'
        state: present
        sysctl_file: /etc/sysctl.conf
        reload: yes

    - name: Verify swap is enabled
      command: swapon --show
      register: final_swap_status
      changed_when: false

    - name: Display final swap status
      debug:
        msg: "{{ final_swap_status.stdout }}"
