---
- name: Smoke test - verify Ansible connection and sudo rights
  hosts: all
  gather_facts: no

  tasks:
    - name: Test connection
      ping:

    - name: Check current user
      command: whoami
      register: current_user
      changed_when: false

    - name: Display current user
      debug:
        msg: "Connected as user: {{ current_user.stdout }}"

    - name: Test sudo privileges
      become: yes
      command: whoami
      register: sudo_user
      changed_when: false

    - name: Display sudo user
      debug:
        msg: "Sudo executes as: {{ sudo_user.stdout }}"

    - name: Verify sudo returns root
      assert:
        that:
          - sudo_user.stdout == "root"
        success_msg: "✓ Sudo privileges verified - user can execute as root"
        fail_msg: "✗ Sudo privileges failed - expected 'root', got '{{ sudo_user.stdout }}'"

    - name: Final success message
      debug:
        msg: "✓ All checks passed! Ansible connection and sudo rights are working correctly."
